Added Dark Theme option
dawsonbooth/react-repo-card pull request #23
Opened 2022-04-13 06:59 UTC by Monochromish

Added a dark theme boolean parameter, easy to use and works perfectly fine!
Also updated the version in the package.json and explained how to use the dark theme option in README.
Here's an example of how it works and looks ⬇️ 

```js
<div style={{ width: '405px' }}>
<RepoCard username="Monochromish" repository="Kalopsia-Bot" useDarkTheme={true} /> // When useDarkTheme is set to true
</div>
<br></br>
<div style={{ width: '405px' }}>
<RepoCard username="prizm-project" repository="Prizm-Website" useDarkTheme={false} /> // When useDarkTheme is set to false
</div>
<br></br>
<div style={{ width: '405px' }}>
<RepoCard username="Monochromish" repository="discord-activities" /> // When useDarkTheme is not specified at all
</div>
```
![image](https://user-images.githubusercontent.com/79590499/163118379-195b6190-25d9-4ef2-b4da-9c88c8c9972e.png)

Thank you!

2022-04-14 20:48 UTC, dawsonbooth commented
Hey, love this! I'll take a look as soon as I find the time :)

2022-04-14 21:33 UTC, dawsonbooth commented
Eventually we'll want the ability to customize all the colors (perhaps with class overrides), but a simple dark mode switch for the background color is good for now

2022-04-14 21:34 UTC, dawsonbooth requested changes

2022-04-14 21:34 UTC, dawsonbooth commented on package.json
> +  "version": "1.2.2",
Seems more like a minor version bump to me

```suggestion
  "version": "1.3.0",
```

2022-04-14 21:34 UTC, dawsonbooth commented on src/index.tsx
> +  var bgColor;
This can be replaced with a ternary (i.e. `const bgColor = useDarkTheme ? "#0d1117" : "white"`) and should be placed below the hooks

2022-04-14 21:34 UTC, dawsonbooth commented on src/index.tsx
> +  useDarkTheme: boolean
Let's rename this to "dark" and use it as an optional flag.

```suggestion
  dark?: boolean
```

2022-04-14 21:35 UTC, dawsonbooth requested changes

2022-04-14 21:35 UTC, dawsonbooth commented on src/index.tsx
> +  var bgColor;
This can be replaced with a ternary (i.e. `const bgColor = useDarkTheme ? "#0d1117" : "white"`) and should be placed below the hooks

2022-04-14 21:36 UTC, dawsonbooth commented on src/index.tsx
> +  var bgColor;
GitHub is being weird, I'm referring to this block:

```ts
var bgColor;
  if (useDarkTheme == true) {
    bgColor = "#0d1117";
  } else {
    bgColor = "white"
  }
```

2022-04-15 16:37 UTC, Monochromish commented
Please review it again, sorry for the inconvenience!

2022-04-15 19:10 UTC, merged

2022-04-15 19:12 UTC, dawsonbooth commented
LGTM! Will publish an update soon. Feel free to play around with the updated card in the storybook!